apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot
    app.kubernetes.io/part-of: appstudio
  name: java-springboot
  namespace: shebert
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: java-springboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: java-springboot
    spec:
      containers:
      - image: quay.io/psturc/test-images-protected:shebert-java-springboot
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
